name: mind_map_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  forui: ^0.14.1 # UI
  provider: ^6.1.5+1 # 状态管理

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  file_selector: # 文件选择器.鸿蒙适配

dependency_overrides:
  file_selector: # 文件选择器.鸿蒙适配
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/file_selector/file_selector"

flutter:
  uses-material-design: true
