name: mind_map_editor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  archive: ^4.0.7 # 压缩
  file_selector: # 文件选择器.鸿蒙适配
  flutter:
    sdk: flutter
  forui: ^0.14.1 # UI
  provider: ^6.1.5+1 # 状态管理
  path_provider: # 应用可用路径.鸿蒙适配
  share_plus: # 分享.鸿蒙适配
  path: ^1.9.1 # 文件路径
  os_type: ^0.2.2 # 操作系统类型
  uuid: ^4.5.2 # uuid
  flutter_lucide: ^1.7.0 # 图标
  graphview: ^1.5.1 # 图形绘制

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  file_selector: # 文件选择器.鸿蒙适配
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/file_selector/file_selector"
  path_provider: # 应用可用路径.鸿蒙适配
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  share_plus: # 分享.鸿蒙适配
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/share_plus/share_plus
      ref: br_share_plus-v10.1.1_ohos

flutter:
  uses-material-design: true
